# Generated by Django 3.1.14 on 2022-11-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_auto_20221101_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Изображение покемона'),
        ),
    ]
